blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Community Support
    url: https://github.com/utmstack/UTMStack/discussions/categories/q-a
    about: Please ask and answer questions as a discussion thread

  - name: ğŸ›Ÿ Commercial Support
    url: https://support.utmstack.com
    about: If you have a commercial support agreement, please file a ticket.

  - name: ğŸ™ï¸ UTMStack Enterprise
    url: https://calendar.app.google/SUCGayUduYReUvxM9
    about: To learn about UTMStack's enterprise edition and how we can assist your company, arrange a consultation with our sales representatives.
