# This is a basic workflow to help you get started with Actions

name: UTM MUTATE BUILD PROD

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  paths:
      - 'mutate/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    uses: ./.github/workflows/build-image-mutate.yml
    with:
      image_name: mutate
      environment: v10
      branch: master
      tag_message: "Automatic Tag Deployed to production"