name: Runner
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      microservice:
        required: true
        type: string

jobs:
  prepare_deployment:
    name: Prepare deployment - ${{inputs.microservice}}
    runs-on: ubuntu-latest
    outputs:
      tech: ${{ steps.get_tech.outputs.tech }}
    steps:
      - uses: actions/checkout@v4

      - name: Determine Tech
        id: get_tech
        run: |
          folder_changed="${{inputs.microservice}}"
          if [[ "$folder_changed" == "agent-manager" ]]; then
            tech="golang"
          elif [[ "$folder_changed" == "backend" ]]; then
            tech="java-11"
          elif [[ "$folder_changed" == "frontend" ]]; then
            tech="frontend"
          elif [[ "$folder_changed" == "user-auditor" || "web-pdf" ]]; then
            tech="java"
          else
            tech="unknown"
          fi
          echo $tech
          echo "::set-output name=tech::$tech"
        shell: bash

  basic_deployment:
    name: Basic deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'basic' }}
    uses: ./.github/workflows/used-docker-basic.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.environment}}
  
  frontend_deployment:
    name: Frontend deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'frontend' }}
    uses: ./.github/workflows/used-docker-frontend.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.environment}}

  golang_deployment:
    name: Golang deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'golang' }}
    uses: ./.github/workflows/used-docker-golang.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.environment}}

  java_11_deployment:
    name: Java 11 deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'java-11' }}
    uses: ./.github/workflows/used-docker-java-11.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.environment}}

  java_deployment:
    name: Java deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'java' }}
    uses: ./.github/workflows/used-docker-java.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.environment}}
